---

- hosts: esgf_slcs_servers
  remote_user: root
  force_handlers: yes
  environment:
    LD_LIBRARY_PATH: /usr/local/conda/envs/esgf-pub/lib/:/usr/local/conda/envs/esgf-pub/lib/python2.7/:/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/mod_wsgi/server
  roles:
    - { role: postgresql, when: configure_databases }
    - { role: nginx, when: use_nginx_proxy }
    - { role: supervisord, when: use_waitress_wsgi }
    - esgf_slcs_server
