---

- name: Install nginx repository
  template: src=templates/nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo

- name: Install nginx
  yum: name=nginx state=latest
  notify:
    - Restart nginx

- name: Remove default server
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify:
    - Restart nginx

- name: Create nginx certificate directory
  file: path=/etc/nginx/certs state=directory

- name: Install main nginx configuration
  copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - Restart nginx

- name: Ensure nginx starts at boot time
  service: name=nginx enabled=yes
