---

- name: Require virtual env
  fail: msg="Waitress can only be used with a virtual env installation"
  when: not use_virtual_env

- name: Install Waitress
  pip:
    name: waitress
    state: latest
    executable: "{{ pip_executable }}"
  become: yes
  become_user: "{{ application_user }}"
  notify:
    - Restart ESGF SLCS Server

- name: Install supervisord config
  template:
    src: templates/supervisord.conf.j2
    dest: /etc/supervisord.d/esgf_slcs_server.conf
  notify:
    - Restart supervisord
