---

- name: Make config directory
  file: path={{ application_home }}/conf/ca state=directory
  become: yes
  become_user: "{{ application_user }}"

- name: Set CA location facts
  set_fact:
    onlineca_trustroots_dir: "{{ application_home }}/conf/ca/trustroots"
    onlineca_cert_file: "{{ application_home }}/conf/ca/onlineca.crt"
    onlineca_key_file: "{{ application_home }}/conf/ca/onlineca.key"
    ## NOTE: These certificates are just for testing, and have no correspondence
    #        with the chain of trust
    onlineca_cacert_chain_filepaths:
      - "{{ application_home }}/conf/ca/trustroots/08bd99c7.0"
      - "{{ application_home }}/conf/ca/trustroots/ade0138a.0"

- name: Install test CA trustroots
  copy: src=files/test_ca/trustroots/ dest={{ onlineca_trustroots_dir }}
  become: yes
  become_user: "{{ application_user }}"

- name: Install test CA certificate file
  copy: src=files/test_ca/onlineca.crt dest={{ onlineca_cert_file }}
  become: yes
  become_user: "{{ application_user }}"

- name: Install OnlineCA private key file
  copy: src=files/test_ca/onlineca.key dest={{ onlineca_key_file }} mode="u=r,g=,o="
  become: yes
  become_user: "{{ application_user }}"
