---

- name: Set code_location fact
  set_fact:
    code_location: "{{ application_home }}/src/esgf_slcs_server"

- name: Clone ESGF SLCS Server from Github
  git:
    repo: https://github.com/ESGF/esgf-slcs-server.git
    version: "{{ esgf_slcs_server_version }}"
    dest: "{{ code_location }}"
  become: yes
  become_user: "{{ application_user }}"

- name: Install ESGF SLCS Server dependencies
  pip:
    executable: /usr/local/conda/envs/esgf-pub/bin/pip
    requirements: "{{ code_location }}/requirements.txt"
    extra_args: --user
  become: yes
  become_user: "{{ application_user }}"

- name: Install ESGF SLCS Server
  pip:
    executable: /usr/local/conda/envs/esgf-pub/bin/pip
    name: "{{ code_location }}"
    extra_args: "--no-deps -e"
  become: yes
  become_user: "{{ application_user }}"
  notify:
    - Restart ESGF SLCS Server
