---

- include: install.yml

- include: configure-databases.yml
  when: configure_databases

- include: install-test-ca.yml
  when: install_test_ca

- include: configure-application.yml

- include: configure-waitress.yml
  when: use_waitress_wsgi

- include: configure-nginx.yml
  when: use_nginx_proxy
