---

- name: Install pip for system Python
  yum: name={{ item }} state=latest
  with_items:
    - epel-release
    - python-pip

- name: Install supervisord
  pip: name=supervisor state=latest executable=pip
  notify:
    - Restart supervisord

- name: Downgrade meld3 (see https://github.com/puphpet/puphpet/issues/1492)
  pip: name=meld3 version=1.0.0 executable=pip
  notify:
    - Restart supervisord

- name: Create /etc/supervisord.d directory
  file: path=/etc/supervisord.d state=directory

- name: Create /var/log/supervisor directory
  file: path=/var/log/supervisor state=directory

- name: Install supervisord init.d script
  copy: src=files/supervisord.initd dest=/etc/init.d/supervisord mode=0755

- name: Install /etc/supervisord.conf config
  copy: src=files/supervisord.conf dest=/etc/supervisord.conf
  notify:
    - Restart supervisord

- name: Ensure supervisord starts at boot time
  service: name=supervisord enabled=yes
